import unidecode
import re
import ftfy

def clean_bert(resulta):   
    result = ftfy.fix_text(resulta)
    result=result.replace("nº", "" )
    result=result.replace("n.º" ,"" )
    result=result.replace("n°", "")
    result=result.replace("lei estadual nº ", "lei") 
    result=result.replace("lei federal nº ", "lei") 
    result=result.replace("lei municipal nº ", "lei")
    result=result.replace("fl.", "fls.")
    result=result.replace("p.", "pp.")
    result=result.replace("art.", "artigo")
    result=result.replace("\n", " ")
    result=result.replace("dr", "dr.")
    result=result.replace("dra", "dr.")
    result=result.replace("ª", "")
    result=result.replace("º", "")
    result=result.replace("°", "")
    result=result.replace(":", " : ") 
    result=re.sub(' +', ' ', result)
    
    return(result)

def clean(resulta):  
    result=unidecode.unidecode(resulta)
    result=result.lower()
    result=" "+result #colocando espaço no começo
    result=re.sub('\d', ' ', result)
    result=result.replace("lei ", "lei_")
    result=result.replace("lei nº ", "lei_")
    result=result.replace("lei n.º" ,"lei_")
    result=result.replace("lei estadual nº ", "lei_") 
    result=result.replace("lei federal nº ", "lei_") 
    result=result.replace("lei municipal nº ", "lei_")
    result=result.replace("fl. ", "fls. ")
    result=result.replace("fls. ", "fls_") 
    result=result.replace("p. ", "pp. ")
    result=result.replace("pp. ", "pp_")
    result=result.replace("art. ", "art_") 
    result=result.replace("artigo ", "art_")
    result=result.replace("inciso ", "inciso_") 
    result=result.replace("nº ", "nº_")
    result=result.replace("n° ", "nº_")
    result=result.replace("º ", "º")
    result=result.replace("ª ", "ª")
    result=result.replace("oab ", "oab_")
    result=result.replace("r$ ", "r$_")
    result=result.replace("\n", " ")
    result=result.replace("dr ", "dr_")
    result=result.replace("dr. ", "dr_")
    result=result.replace("dra ", "dr_")
    result=result.replace("dra. ", "dr_")
    result=result.replace("adv: ", "adv_") 
    
    result=result.replace("/", " ")
    result=result.replace("|", " ")
    result=result.replace("+", " ")
    result=result.replace(".", " ")
    result=result.replace(",", " ")
    result=result.replace(":", " ")
    result=result.replace(";", " ")
    result=result.replace("!", " ")
    result=result.replace("?", " ")
    result=result.replace(">", " ")
    result=result.replace("=", " ")
    result=result.replace("§", " ")
    result=result.replace(" - ", " ")
    result=result.replace(" _ ", " ")
    result=result.replace("&", " ")
    result=result.replace("*", " ")
    result=result.replace("(", " ")
    result=result.replace(")", " ")
    result=result.replace("ª", " ")
    result=result.replace("º", " ")
    result=result.replace("%", " ")
    result=result.replace("[", " ")
    result=result.replace("]", " ")
    result=result.replace("{", " ")
    result=result.replace("}", " ")
    result=result.replace("'", " ")
    result=result.replace('"', " ")
    result=result.replace("“", " ")
    result=result.replace("”", " ")
    result=re.sub(' +', ' ', result)
    result=result.strip()
    
    return(result)
